/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AssessoresRouteImport } from './routes/assessores'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as InvestidorRouteImport } from './routes/investidor'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PosseRouteImport } from './routes/posse'
import { Route as RegularizacaoRouteImport } from './routes/regularizacao'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as AuthenticatedProjetosEditarRouteImport } from './routes/_authenticated/projetos..editar'
import { Route as AuthenticatedProjetosNovoRouteImport } from './routes/_authenticated/projetos.novo'
import { Route as ProjetosIdIndexRouteImport } from './routes/projetos.$id.index'
import { Route as ProjetosIdDocumentosRouteImport } from './routes/projetos.$id.documentos'
import { Route as ProjetosIdFinanceiroRouteImport } from './routes/projetos.$id.financeiro'
import { Route as ProjetosIdTarefasRouteImport } from './routes/projetos.$id.tarefas'
import { Route as AuthenticatedProjetosIdEditarRouteImport } from './routes/_authenticated/projetos.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessoresRoute = AssessoresRouteImport.update({
  id: '/assessores',
  path: '/assessores',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestidorRoute = InvestidorRouteImport.update({
  id: '/investidor',
  path: '/investidor',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PosseRoute = PosseRouteImport.update({
  id: '/posse',
  path: '/posse',
  getParentRoute: () => rootRouteImport,
} as any)
const RegularizacaoRoute = RegularizacaoRouteImport.update({
  id: '/regularizacao',
  path: '/regularizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetosEditarRoute =
  AuthenticatedProjetosEditarRouteImport.update({
    id: '/projetos/editar',
    path: '/projetos/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosNovoRoute =
  AuthenticatedProjetosNovoRouteImport.update({
    id: '/projetos/novo',
    path: '/projetos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ProjetosIdIndexRoute = ProjetosIdIndexRouteImport.update({
  id: '/projetos/$id/',
  path: '/projetos/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdDocumentosRoute = ProjetosIdDocumentosRouteImport.update({
  id: '/projetos/$id/documentos',
  path: '/projetos/$id/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdFinanceiroRoute = ProjetosIdFinanceiroRouteImport.update({
  id: '/projetos/$id/financeiro',
  path: '/projetos/$id/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdTarefasRoute = ProjetosIdTarefasRouteImport.update({
  id: '/projetos/$id/tarefas',
  path: '/projetos/$id/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetosIdEditarRoute =
  AuthenticatedProjetosIdEditarRouteImport.update({
    id: '/projetos/$id/editar',
    path: '/projetos/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessores': typeof AssessoresRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/imoveis': typeof ImoveisRoute
  '/investidor': typeof InvestidorRoute
  '/notificacoes': typeof NotificacoesRoute
  '/obras': typeof ObrasRoute
  '/perfil': typeof PerfilRoute
  '/posse': typeof PosseRoute
  '/regularizacao': typeof RegularizacaoRoute
  '/resultados': typeof ResultadosRoute
  '/tarefas': typeof TarefasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/projetos/editar': typeof AuthenticatedProjetosEditarRoute
  '/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/projetos/$id/documentos': typeof ProjetosIdDocumentosRoute
  '/projetos/$id/financeiro': typeof ProjetosIdFinanceiroRoute
  '/projetos/$id/tarefas': typeof ProjetosIdTarefasRoute
  '/projetos/$id/': typeof ProjetosIdIndexRoute
  '/projetos/$id/editar': typeof AuthenticatedProjetosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessores': typeof AssessoresRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/imoveis': typeof ImoveisRoute
  '/investidor': typeof InvestidorRoute
  '/notificacoes': typeof NotificacoesRoute
  '/obras': typeof ObrasRoute
  '/perfil': typeof PerfilRoute
  '/posse': typeof PosseRoute
  '/regularizacao': typeof RegularizacaoRoute
  '/resultados': typeof ResultadosRoute
  '/tarefas': typeof TarefasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/projetos': typeof ProjetosIndexRoute
  '/projetos/editar': typeof AuthenticatedProjetosEditarRoute
  '/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/projetos/$id/documentos': typeof ProjetosIdDocumentosRoute
  '/projetos/$id/financeiro': typeof ProjetosIdFinanceiroRoute
  '/projetos/$id/tarefas': typeof ProjetosIdTarefasRoute
  '/projetos/$id': typeof ProjetosIdIndexRoute
  '/projetos/$id/editar': typeof AuthenticatedProjetosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assessores': typeof AssessoresRoute
  '/dashboard': typeof DashboardRoute
  '/documentos': typeof DocumentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/imoveis': typeof ImoveisRoute
  '/investidor': typeof InvestidorRoute
  '/notificacoes': typeof NotificacoesRoute
  '/obras': typeof ObrasRoute
  '/perfil': typeof PerfilRoute
  '/posse': typeof PosseRoute
  '/regularizacao': typeof RegularizacaoRoute
  '/resultados': typeof ResultadosRoute
  '/tarefas': typeof TarefasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/_authenticated/projetos/editar': typeof AuthenticatedProjetosEditarRoute
  '/_authenticated/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/projetos/$id/documentos': typeof ProjetosIdDocumentosRoute
  '/projetos/$id/financeiro': typeof ProjetosIdFinanceiroRoute
  '/projetos/$id/tarefas': typeof ProjetosIdTarefasRoute
  '/projetos/$id/': typeof ProjetosIdIndexRoute
  '/_authenticated/projetos/$id/editar': typeof AuthenticatedProjetosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessores'
    | '/dashboard'
    | '/documentos'
    | '/financeiro'
    | '/imoveis'
    | '/investidor'
    | '/notificacoes'
    | '/obras'
    | '/perfil'
    | '/posse'
    | '/regularizacao'
    | '/resultados'
    | '/tarefas'
    | '/admin/configuracoes'
    | '/admin/usuarios'
    | '/projetos/'
    | '/projetos/editar'
    | '/projetos/novo'
    | '/projetos/$id/documentos'
    | '/projetos/$id/financeiro'
    | '/projetos/$id/tarefas'
    | '/projetos/$id/'
    | '/projetos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessores'
    | '/dashboard'
    | '/documentos'
    | '/financeiro'
    | '/imoveis'
    | '/investidor'
    | '/notificacoes'
    | '/obras'
    | '/perfil'
    | '/posse'
    | '/regularizacao'
    | '/resultados'
    | '/tarefas'
    | '/admin/configuracoes'
    | '/admin/usuarios'
    | '/projetos'
    | '/projetos/editar'
    | '/projetos/novo'
    | '/projetos/$id/documentos'
    | '/projetos/$id/financeiro'
    | '/projetos/$id/tarefas'
    | '/projetos/$id'
    | '/projetos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assessores'
    | '/dashboard'
    | '/documentos'
    | '/financeiro'
    | '/imoveis'
    | '/investidor'
    | '/notificacoes'
    | '/obras'
    | '/perfil'
    | '/posse'
    | '/regularizacao'
    | '/resultados'
    | '/tarefas'
    | '/admin/configuracoes'
    | '/admin/usuarios'
    | '/projetos/'
    | '/_authenticated/projetos/editar'
    | '/_authenticated/projetos/novo'
    | '/projetos/$id/documentos'
    | '/projetos/$id/financeiro'
    | '/projetos/$id/tarefas'
    | '/projetos/$id/'
    | '/_authenticated/projetos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssessoresRoute: typeof AssessoresRoute
  DashboardRoute: typeof DashboardRoute
  DocumentosRoute: typeof DocumentosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  ImoveisRoute: typeof ImoveisRoute
  InvestidorRoute: typeof InvestidorRoute
  NotificacoesRoute: typeof NotificacoesRoute
  ObrasRoute: typeof ObrasRoute
  PerfilRoute: typeof PerfilRoute
  PosseRoute: typeof PosseRoute
  RegularizacaoRoute: typeof RegularizacaoRoute
  ResultadosRoute: typeof ResultadosRoute
  TarefasRoute: typeof TarefasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
  ProjetosIdDocumentosRoute: typeof ProjetosIdDocumentosRoute
  ProjetosIdFinanceiroRoute: typeof ProjetosIdFinanceiroRoute
  ProjetosIdTarefasRoute: typeof ProjetosIdTarefasRoute
  ProjetosIdIndexRoute: typeof ProjetosIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessores': {
      id: '/assessores'
      path: '/assessores'
      fullPath: '/assessores'
      preLoaderRoute: typeof AssessoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investidor': {
      id: '/investidor'
      path: '/investidor'
      fullPath: '/investidor'
      preLoaderRoute: typeof InvestidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posse': {
      id: '/posse'
      path: '/posse'
      fullPath: '/posse'
      preLoaderRoute: typeof PosseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regularizacao': {
      id: '/regularizacao'
      path: '/regularizacao'
      fullPath: '/regularizacao'
      preLoaderRoute: typeof RegularizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos/editar': {
      id: '/_authenticated/projetos/editar'
      path: '/projetos/editar'
      fullPath: '/projetos/editar'
      preLoaderRoute: typeof AuthenticatedProjetosEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/novo': {
      id: '/_authenticated/projetos/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof AuthenticatedProjetosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/projetos/$id/': {
      id: '/projetos/$id/'
      path: '/projetos/$id'
      fullPath: '/projetos/$id/'
      preLoaderRoute: typeof ProjetosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id/documentos': {
      id: '/projetos/$id/documentos'
      path: '/projetos/$id/documentos'
      fullPath: '/projetos/$id/documentos'
      preLoaderRoute: typeof ProjetosIdDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id/financeiro': {
      id: '/projetos/$id/financeiro'
      path: '/projetos/$id/financeiro'
      fullPath: '/projetos/$id/financeiro'
      preLoaderRoute: typeof ProjetosIdFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id/tarefas': {
      id: '/projetos/$id/tarefas'
      path: '/projetos/$id/tarefas'
      fullPath: '/projetos/$id/tarefas'
      preLoaderRoute: typeof ProjetosIdTarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos/$id/editar': {
      id: '/_authenticated/projetos/$id/editar'
      path: '/projetos/$id/editar'
      fullPath: '/projetos/$id/editar'
      preLoaderRoute: typeof AuthenticatedProjetosIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProjetosEditarRoute: typeof AuthenticatedProjetosEditarRoute
  AuthenticatedProjetosNovoRoute: typeof AuthenticatedProjetosNovoRoute
  AuthenticatedProjetosIdEditarRoute: typeof AuthenticatedProjetosIdEditarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProjetosEditarRoute: AuthenticatedProjetosEditarRoute,
  AuthenticatedProjetosNovoRoute: AuthenticatedProjetosNovoRoute,
  AuthenticatedProjetosIdEditarRoute: AuthenticatedProjetosIdEditarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssessoresRoute: AssessoresRoute,
  DashboardRoute: DashboardRoute,
  DocumentosRoute: DocumentosRoute,
  FinanceiroRoute: FinanceiroRoute,
  ImoveisRoute: ImoveisRoute,
  InvestidorRoute: InvestidorRoute,
  NotificacoesRoute: NotificacoesRoute,
  ObrasRoute: ObrasRoute,
  PerfilRoute: PerfilRoute,
  PosseRoute: PosseRoute,
  RegularizacaoRoute: RegularizacaoRoute,
  ResultadosRoute: ResultadosRoute,
  TarefasRoute: TarefasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
  ProjetosIdDocumentosRoute: ProjetosIdDocumentosRoute,
  ProjetosIdFinanceiroRoute: ProjetosIdFinanceiroRoute,
  ProjetosIdTarefasRoute: ProjetosIdTarefasRoute,
  ProjetosIdIndexRoute: ProjetosIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
